web_app/Controllers/AdminController.cs
using web_app.Models;
using web_app.BLL;
using web_app.DAL;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Data;

namespace web_app.Controllers
{
        [Authorize]
    public class AdminController : Controller
    {
        private static string ConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ToString();
        public AdminController()
        {
        }
        public AdminController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Admin
        public ActionResult Organisation()
        {
            return View();
        }
        // GET: Admin
        public ActionResult spHelper()
        {
            return View();
        }
        public ActionResult OrganisationDetails()
        {
            Organisation organisation = AdminCore.get_organisation();
            return View(organisation);
        }
        public ActionResult WorkArea()
        {
            return View();
        }
      

        public ActionResult ChangePassword_win(string username)
        {
            ViewBag.username = username;
            return View();
        }

        public ActionResult Sysconfig()
        {
            Config config = AdminCore.get_sysconfig();

            ViewBag.list_dateformat = new SelectList(AdminCore.get_lookups("date-format"), "id", "value", config.dateformat);
            ViewBag.list_startday = new SelectList(AdminCore.get_lookups("week-startday"), "id", "value", config.startday);
            ViewBag.list_com_roles = new SelectList(AdminCore.get_roles(), "role_id", "role_name", config.com_role);
            ViewBag.list_man_roles = new SelectList(AdminCore.get_roles(), "role_id", "role_name", config.man_role);
            return View(config);
        }
        [HttpPost]
        public ActionResult Sysconfig(FormCollection _form)
        {
            string dateformat = _form["ddlDateFormat"].ToString();
            string startday = _form["ddlStartDay"].ToString();
            string com_role = _form["ddlCompanyRole"].ToString();
            string man_role = _form["ddlManufactureRole"].ToString();


            using (lidEntities dbo = new lidEntities())
            {
                b_config _config = dbo.b_config.FirstOrDefault();

                if (_config == null)
                {
                    _config = new b_config();
                    
                    _config.dateformat = dateformat;
                    _config.startday = startday;
                    _config.com_role = com_role.ToLongOrDefault();
                    _config.man_role = man_role.ToLongOrDefault();

                    dbo.b_config.Add(_config);
                    dbo.SaveChanges();
                }
                else
                {
                    _config.dateformat = dateformat;
                    _config.startday = startday;
                    _config.com_role = com_role.ToLongOrDefault();
                    _config.man_role = man_role.ToLongOrDefault();

                    dbo.Entry(_config).State = System.Data.Entity.EntityState.Modified;
                    dbo.SaveChanges();
                }
            }

            return RedirectToAction("Sysconfig");
        }
        //public ActionResult schedule_ view(string staff_id, string staff_surname, string weekday, string dept_id = "0")
        //{
        //    ViewData["_staff_id"] = staff_id;
        //    ViewData["_dept_id"] = dept_id;
        //    ViewData["_staff_surname"] = staff_surname;
        //    ViewData["dayname"] = weekday;
        //    return PartialView();
        //}
        public ActionResult schedule_view(string staff_id, string weekday, string dept_id = "0")
        {
            ViewData["_staff_id"] = staff_id;
            ViewData["_dept_id"] = dept_id;
            ViewData["_staff_surname"] = "";
            ViewData["dayname"] = weekday;
            return PartialView();
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult lnkDepartment(FormCollection _form, string _weekday = "", int _pos_id = 0, string _uri = "")
        {
            string dept_id = _form["ddlDept"].ToString();
            return RedirectToAction(_uri, new { _weekday = _weekday, _dept_id = dept_id, _pos_id = _pos_id });
        }

        public ActionResult lnkPosition(FormCollection _form, string _weekday = "", int _dept_id = 0, string _uri = "")
        {
            string pos_id = _form["ddlPosition"].ToString();
            return RedirectToAction(_uri, new { _weekday = _weekday, _dept_id = _dept_id, _pos_id = pos_id });
        }

        public ActionResult flt_calendar(FormCollection _form, int _dept_id = 0, int _pos_id = 0, string _uri = "")
        {
            string startday = _form["startDate"].ToString();
            return RedirectToAction(_uri, new { _weekday = startday, _dept_id = _dept_id, _pos_id = _pos_id });
        }
   
        [HttpPost]
        public ActionResult AddStaff(FormCollection _form, HttpPostedFileBase upload)
        {
            long staff_id = 0;
            string ddlTitle = _form["ddlTitle"].ToString();
            string initials = _form["initials"].ToString();
            string name = _form["name"].ToString();
            string surname = _form["surname"].ToString();
            string ddlIDType = _form["ddlIDType"].ToString();
            string ddlCounntyOfIssue = _form["ddlCountryOfIssue"].ToString();
            string idnumber = _form["idnumber"].ToString();
            string dob = _form["dob"].ToString();
            string ddlGender = _form["ddlGender"].ToString();
            string ddlRace = _form["ddlRace"].ToString();
            string ddlMaritalstatus = _form["ddlMaritalstatus"].ToString();
            string ddlNationality = _form["ddlNationality"].ToString();
            string structure_id = _form["org_hierarchy"].ToString();
            //string upload = _form["upload"].ToString();
            string chkActive = _form["chkActive"].ToString();
            string empno = _form["empno"].ToString();
            string startdate = _form["startdate"].ToString();
            string emptype = _form["ddlEmployementType"].ToString();
            string ddlPositionHeld = _form["ddlPositionHeld"].ToString();
            string ddlQualification = _form["ddlQualification"].ToString();
            string qualificationdate = _form["qualificationdate"].ToString();
            string ddlDepartment = _form["ddlDepartment"].ToString();
            //string ddlStructureLevel = _form["ddlStructureLevel"].ToString();
            string telw = _form["telw"].ToString();
            string telh = _form["telh"].ToString();
            string email = _form["email"].ToString();
            string mobile = _form["mobile"].ToString();
            string spousename = _form["spousename"].ToString();
            string spousenumber = _form["spousenumber"].ToString();
            string nextkinname = _form["nextkinname"].ToString();
            string nextkinnumber = _form["nextkinnumber"].ToString();
            string houseno = _form["houseno"].ToString();
            string pobox = _form["pobox"].ToString();
            string streetname = _form["streetname"].ToString();
            string postoffice = _form["postoffice"].ToString();
            string addresssurburd = _form["addresssurburd"].ToString();
            string postsurburd = _form["postsurburd"].ToString();
            string addresstown = _form["addresstown"].ToString();
            string posttown = _form["posttown"].ToString();
            string addresscode = _form["addresscode"].ToString();
            string postcode = _form["postcode"].ToString();


            string filename = "";
            if (upload != null && upload.ContentLength > 0)
            {
                string ext = Path.GetFileName(upload.FileName);
                filename = ext;
                if (ext.Split('.').Length > 1)
                {
                    filename = empno + "." + ext.Split('.')[ext.Split('.').Length - 1].ToString();
                }
                var path = Path.Combine(Server.MapPath("~/Photo/Staff"), filename);
                upload.SaveAs(path);
            }

            using (lidEntities dbo = new lidEntities())
            {
                b_staff _staff = new b_staff();
                _staff.staff_name = name;
                _staff.staff_surname = surname;
                _staff.emp_type = Convert.ToInt32(emptype);
                _staff.staff_title = ddlTitle.ToLongOrDefault();
                _staff.staff_number = empno;
                _staff.staff_idnumber = idnumber;
                _staff.staff_mobile = mobile;
                _staff.staff_telephone = telw;
                _staff.staff_email = email;
                _staff.photo = filename;
                _staff.isActive = true;
                _staff.isDeleted = false;
                _staff.emp_date = Convert.ToDateTime(startdate);
                _staff.date_created = DateTime.Now;



                _staff.staff_initials = initials;
                _staff.idType_id = ddlIDType.ToLongOrDefault();
                _staff.counntyOfIssue_id = ddlCounntyOfIssue.ToLongOrDefault();
                _staff.dob = dob.ToDateTimeOrDefault();
                _staff.gender_id = ddlGender.ToLongOrDefault();

web_app/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web_app.Controllers
{
    public class HelpController : Controller
    {
        // GET: Help
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SQL()
        {
            return View();
        }
    }
}

web_app/Views/partial/_side_menu.cshtml
@using web_app.BLL;
@using web_app.Models;

@{
    string _action = ViewContext.RouteData.Values["action"].ToString();
    string _controller = ViewContext.RouteData.Values["controller"].ToString();
    List<Menus> menus = AdminCore.get_userwebsubmenus(User.Identity.Name, _controller);
}

<div class="vernav2 iconmenu">
    <ul>
        @{
            foreach (Menus menu in menus)
            {
                if (@menu.menu_action == null)
                {
                    <li>@menu.menu_name</li>
                }
                else
                {
                    <li class="@((@_action == @menu.menu_action) ? "current" : "")"><i style="padding: 4px 12px;" class="fa @menu.menu_icon"></i><a href="@Url.Action(@menu.menu_action, @menu.menu_controller)">@menu.menu_name</a></li>
                    }
                }
            }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_admin.cshtml
@using web_app.BLL;
@using web_app.Models;

@{
    string _action = ViewContext.RouteData.Values["action"].ToString();
    string _controller = ViewContext.RouteData.Values["controller"].ToString();
    List<Menus> menus = AdminCore.get_userwebsubmenus(User.Identity.Name, _controller);
}

<div class="vernav2 iconmenu">
    <ul>
        @{
            foreach (Menus menu in menus)
            {
                if (@menu.menu_action == null)
                {
                    <li>@menu.menu_name</li>
                }
                else
                {
                    <li class="@((@_action == @menu.menu_action) ? "current" : "")"><i style="padding: 4px 12px;" class="fa @menu.menu_icon"></i><a href="@Url.Action(@menu.menu_action, @menu.menu_controller)">@menu.menu_name</a></li>
                    }
                }
            }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_help.cshtml
<div class="vernav2 iconmenu">
    <ul>
        @{
            string page = ViewData["_current"].ToString();
            string css = "current";
            string css_non = "current_off";
            <li class="@((page == "Index") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Index","Help")" class="calendar">Help Documentation</a></li>
        }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_home.cshtml
<div class="vernav2 iconmenu">
    <ul>
        @{
            string page = ViewData["_current"].ToString();
            string css = "current";
            string css_non = "current_off";
            <li class="@((page == "Home") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-home"></i> <a href="@Url.Action("Index", "Home")" class="calendar">Dashboard</a></li>
            <li class="@((page == "Calendar") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-calendar"></i> <a href="@Url.Action("Calendar", "Home")" class="calendar">Calendar</a></li>
            <li class="@((page == "Queue") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i> <a href="@Url.Action("Queue", "Home")">Work Queue</a></li>
            @*<li class="@((page == "Tempo") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-users"></i> <a href="@Url.Action("Tempo", "Home")" class="calendar">Staff Tempo</a></li>
            <li class="@((page == "Stats") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-car"></i> <a href="@Url.Action("Stats", "Home")" class="calendar">Stats</a></li>*@
        }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_hr.cshtml
@using web_app.BLL;
@using web_app.Models;

@{
    string _action = ViewContext.RouteData.Values["action"].ToString();
    string _controller = ViewContext.RouteData.Values["controller"].ToString();
    List<Menus> menus = AdminCore.get_userwebsubmenus(User.Identity.Name, _controller);
}

<div class="vernav2 iconmenu">
    <ul>
        @{
            foreach (Menus menu in menus)
            {
                if (@menu.menu_action == null)
                {
                    <li>@menu.menu_name</li>
                }
                else
                {
                    <li class="@((@_action == @menu.menu_action) ? "current" : "")"><i style="padding: 4px 12px;" class="fa @menu.menu_icon"></i><a href="@Url.Action(@menu.menu_action, @menu.menu_controller)">@menu.menu_name</a></li>
                }
            }
            @*<li class="@((page == "Index") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Index","HR")" class="calendar">Dashboard</a></li>
            <li>Staff Management</li>
            <li class="@((page == "ShiftTrade") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("AddStaff","Admin")">Add Staff Member</a></li>
            <li class="@((page == "ShiftTrade") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ViewStaff","Admin")">View Staff Members</a></li>
            <li>Staff Requests</li>
            <li class="@((page == "LeaveRequests") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("LeaveRequests", "HR")" class="typo">Leave Requests</a></li>
            <li class="@((page == "ShiftTrade") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ShiftTrade", "HR")" class="typo">Shift Trade</a></li>
            <li>Approve</li>
            <li class="@((page == "ShiftTrade") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ApproveShift","Home")">Staff Schedule</a></li>
            <li class="@((page == "ShiftTrade") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ApproveLeave","Home")">Leave Requests</a></li>
            <li class="@((page == "ShiftTrade") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ApproveTrade","Home")">Shift Trade</a></li>
            <li>Settings</li>
            <li class="@((page == "Settings") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Settings", "HR")" class="calendar">Organisation Settings</a></li>
            <li class="@((page == "StaffSettings") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("StaffSettings", "HR")" class="calendar">Staff Settings</a></li>
            <li class="@((page == "ShiftSettings") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ShiftSettings", "HR")" class="calendar">Shift Settings</a></li>*@

            @* <li class="@((page == "Hourlyrates") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("LeaveRequests", "HR")" class="typo">Hourly Rates</a></li>
                <li class="@((page == "ShiftTrade") ? @css : @css_non)"><a href="@Url.Action("ShiftTrade", "HR")" class="typo">Shift Trade</a></li>*@
        }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_items.cshtml
@using web_app.BLL;
@using web_app.Models;

@{
    string _action = ViewContext.RouteData.Values["action"].ToString();
    string _controller = ViewContext.RouteData.Values["controller"].ToString();
    List<Menus> menus = AdminCore.get_userwebsubmenus(User.Identity.Name, _controller);
}

<div class="vernav2 iconmenu">
    <ul>
        @{
            foreach (Menus menu in menus)
            {
                if (@menu.menu_action == null)
                {
                    <li>@menu.menu_name</li>
                }
                else
                {
                    <li class="@((@_action == @menu.menu_action) ? "current" : "")"><i style="padding: 4px 12px;" class="fa @menu.menu_icon"></i><a href="@Url.Action(@menu.menu_action, @menu.menu_controller)">@menu.menu_name</a></li>
                }
            }
             }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_organisation.cshtml
@using web_app.BLL;
@using web_app.Models;

@{
    string _action = ViewContext.RouteData.Values["action"].ToString();
    string _controller = ViewContext.RouteData.Values["controller"].ToString();
    List<Menus> menus = AdminCore.get_userwebsubmenus(User.Identity.Name, _controller);
}

<div class="vernav2 iconmenu">
    <ul>
        @{
            foreach (Menus menu in menus)
            {
                if (@menu.menu_action == null)
                {
                    <li>@menu.menu_name</li>
                }
                else
                {
                    <li class="@((@_action == @menu.menu_action) ? "current" : "")"><i style="padding: 4px 12px;" class="fa @menu.menu_icon"></i><a href="@Url.Action(@menu.menu_action, @menu.menu_controller)">@menu.menu_name</a></li>
                }
            }
            @*<li class="@((page == "Dashboard") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Index","Organisation")" class="calendar">Dashboard</a></li>
            <li>Structure</li>
            <li class="@((page == "Structure") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Structure", "Organisation")" class="calendar">Organisation Structure</a></li>
            <li class="@((page == "StaffStructure") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("StaffStructure", "Organisation")" class="calendar">Staff Structure</a></li>
            <li>Staff</li>
            <li class="@((page == "StaffHours") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("StaffHours", "Organisation")" class="calendar">Staff Hours</a></li>
            <li class="@((page == "OrganisationStaff") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("OrganisationStaff", "Organisation")" class="calendar">Organisation Staff</a></li>
            <li>Details</li>
            <li class="@((page == "Organisation") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Organisation","Organisation")" class="calendar">Organisation Details</a></li>
            <li class="@((page == "DisplayFormats") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("DisplayFormats", "Organisation")" class="calendar">Display Formats</a></li>
            <li>Settings</li>
            <li class="@((page == "Settings") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Settings", "Organisation")" class="calendar">Organisation Settings</a></li>
            <li class="@((page == "StaffSettings") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("StaffSettings", "Organisation")" class="calendar">Staff Settings</a></li>
            <li class="@((page == "ShiftSettings") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ShiftSettings", "Organisation")" class="calendar">Shift Settings</a></li>
            <li>Documents</li>
            <li class="@((page == "UploadDocument") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("UploadDocument", "Organisation")" class="calendar">Upload Document</a></li>
            <li class="@((page == "SettingDocument") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("SettingDocument", "Organisation")" class="calendar">Document Settings</a></li>*@
        }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_profile.cshtml
<div class="vernav2 iconmenu">
    <ul>
        @{
            string page = ViewData["_current"].ToString();
            string css = "current";
            string css_non = "current_off";
            <li class="@((page == "MyProfile") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-user"></i><a href="@Url.Action("MyProfile","Profile")" class="calendar">My Profile</a></li>
            <li class="@((page == "MyCalendar") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-calendar"></i><a href="@Url.Action("MyCalendar","Profile")" class="calendar">My Calendar</a></li>
        }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_roles.cshtml
<div class="vernav2 iconmenu">
    <ul>
            <li ><a href="@Url.Action("LogOut", "Account")" class="typo">Log Out</a></li>
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_schedule.cshtml
@using web_app.BLL;
@using web_app.Models;

@{
    string _action = ViewContext.RouteData.Values["action"].ToString();
    string _controller = ViewContext.RouteData.Values["controller"].ToString();
    List<Menus> menus = AdminCore.get_userwebsubmenus(User.Identity.Name, _controller);
}

<div class="vernav2 iconmenu">
    <ul>
        @{
            foreach (Menus menu in menus)
            {
                if (@menu.menu_action == null)
                {
                    <li>@menu.menu_name</li>
                }
                else
                {
                    <li class="@((@_action == @menu.menu_action) ? "current" : "")"><i style="padding: 4px 12px;" class="fa @menu.menu_icon"></i><a href="@Url.Action(@menu.menu_action, @menu.menu_controller)">@menu.menu_name</a></li>
                }
            }
            @*<li class="@((page == "Index") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Index","Schedule")" class="elements">Dashboard</a></li>
            <li>Schedule Results</li>
            <li class="@((page == "Schedule") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Schedule","Schedule")" class="elements">Staff Schedule</a></li>
            <li class="@((page == "TimeSheet") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("TimeSheet","Schedule")" class="calendar">Time Sheet</a></li>
            <li class="@((page == "StaffHours") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("StaffHours", "Schedule")" class="calendar">Staff Hours</a></li>
            <li>Graphical Charts</li>
            <li class="@((page == "Burndown") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Burndown","Schedule")" class="calendar">Burn Down</a></li>
            <li class="@((page == "Attendance") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Attendance", "Schedule")" class="calendar">Attendance</a></li>*@
            @*<li>Settings</li>
                <li class="@((page == "Distribution") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Distribution", "Schedule")" class="calendar">Distribution</a></li>
                <li class="@((page == "Automation") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("Automation", "Schedule")" class="calendar">Automation</a></li>*@
        }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>

web_app/Views/partial/_side_menu_scheduler.cshtml
@using web_app.BLL;
@using web_app.Models;

@{
    string _action = ViewContext.RouteData.Values["action"].ToString();
    string _controller = ViewContext.RouteData.Values["controller"].ToString();
    List<Menus> menus = AdminCore.get_userwebsubmenus(User.Identity.Name, _controller);
}

<div class="vernav2 iconmenu">
    <ul>
        @{
            foreach (Menus menu in menus)
            {
                if (@menu.menu_action == null)
                {
                    <li>@menu.menu_name</li>
                }
                else
                {
                <li class="@((@_action == @menu.menu_action) ? "current" : "")"><i style="padding: 4px 12px;" class="fa @menu.menu_icon"></i><a href="@Url.Action(@menu.menu_action, @menu.menu_controller)">@menu.menu_name</a></li>
                }
            }
            @*  <li class="@((page == "Index") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-home"></i><a href="@Url.Action("Index","Scheduler")">Dashboard</a>
                  </li><li>Staff Scheduler</li>
                  <li class="@((page == "ManageShifts") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("ManageShifts","Scheduler")">Shift Scheduler </a></li>
                  <li class="@((page == "StaffScheduler") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("StaffScheduler","Scheduler")">Staff Scheduler</a></li>
                  <li>Staff Grouping</li>
                  <li class="@((page == "StaffGrouping") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("StaffGrouping", "Scheduler")">Staff Grouping</a></li>
                <li class="@((page == "AutoScheduler") ? @css : @css_non)"><i style="padding: 4px 12px;" class="fa fa-cog"></i><a href="@Url.Action("AutoScheduler","Scheduler")">Auto Scheduler</a></li>*@
        }
    </ul>
    <a class="togglemenu"></a>
    <br />
    <br />
</div>