web_app/Controllers/ReportsController.cs
using web_app.BLL;
using web_app.DAL;
using web_app.Models;
//using Rotativa;0
//using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using Dapper;
using System.Configuration;
using System.IO;

namespace web_app.Controllers
{
    public class ReportsController : Controller
    {

        private static string ConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ToString();

        private static SqlConnection GetOpenConnection(bool mars = false)
        {
            var cs = ConnectionString;
            if (mars)
            {
                var scsb = new SqlConnectionStringBuilder(cs)
                {
                    MultipleActiveResultSets = true
                };
                cs = scsb.ConnectionString;
            }
            var connection = new SqlConnection(cs);
            connection.Open();
            return connection;
        }

        public ActionResult Index()
        {
            string username = User.Identity.Name;
            List<ReportCategory> cats = ReportCore.get_reportcategory(username);
            ReportsDTO reports = new ReportsDTO();
            reports.cat_list = cats;
            return View(reports);
        }

        public ActionResult ReportParameters(long report_id)
        {
            Reports report = ReportCore.get_report(report_id);
            return View(report);
        }

        public ActionResult DepartmentStaff()
        {
            List<rptDeptWithStaff> data = ReportCore.rpt_deptwithstaff();
            return View(data);
        }

        public ActionResult RecentReports()
        {
            string username = User.Identity.Name;
            List<RptRecentDTO> list = ReportCore.get_RecentReports(username);
            return View(list);
        }

        public ActionResult ManageRecent()
        {
            return View();
        }
        public JsonResult GetRecentReports()
        {
            string username = User.Identity.Name;
            List<RptRecentDTO> list = ReportCore.get_RecentReports(username);
            var json = new JavaScriptSerializer().Serialize(list);
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DelRecentReport(string id)
        {
            AjaxResults res = new AjaxResults();
            using (lidEntities dbo = new lidEntities())
            {
                long _id = id.ToLongOrDefault(0);
                b_recentreports recent = dbo.b_recentreports.Where(x => x.id == _id).FirstOrDefault();
                if (recent != null)
                {
                    dbo.Entry(recent).State = System.Data.Entity.EntityState.Deleted;
                    dbo.SaveChanges();
                    res.code = "1";
                    res.message = "Recent report successfully deleted.";
                }
                else
                {
                    res.code = "0";
                    res.message = "Recent report not found, Please refresh list and try again.";
                }
            }

            var results = new JavaScriptSerializer().Serialize(res);
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPassReport()
        {
            List<PassFailReportDTO> res = new List<PassFailReportDTO>();
            using (lidEntities dbo = new lidEntities())
            {
                using (var cn = GetOpenConnection())
                {
                    string username = User.Identity.Name.ToString();
                    res = cn.Query<PassFailReportDTO>("rpt_get_passinspection", new { username = username }, commandType: CommandType.StoredProcedure).ToList();
                }
                //if (recent != null)
                //{
                //    dbo.Entry(recent).State = System.Data.Entity.EntityState.Deleted;
                //    dbo.SaveChanges();
                //    res.code = "1";
                //    res.message = "Recent report successfully deleted.";
                //}
                //else
                //{
                //    res.code = "0";
                //    res.message = "Recent report not found, Please refresh list and try again.";
                //}
            }

            var results = new JavaScriptSerializer().Serialize(res);
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RecentSettings()
        {
            return View();
        }
        public ActionResult ArchivedReports()
        {
            List<ArchiveDTO> archive = ReportCore.get_archivereports(User.Identity.Name);
            return View(archive);
        }
        public ActionResult ManageArchives()
        {
            return View();
        }
        public JsonResult GetManageArchives()
        {
            string username = User.Identity.Name;
            List<ArchiveDTO> list = ReportCore.get_archivereports(username);
            var json = new JavaScriptSerializer().Serialize(list);
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DelArchivesFiles(string id)
        {
            AjaxResults res = new AjaxResults();
            using (lidEntities dbo = new lidEntities())
            {
                long _id = id.ToLongOrDefault(0);
                b_reportsarchive recent = dbo.b_reportsarchive.Where(x => x.id == _id).FirstOrDefault();
                if (recent != null)
                {
                    dbo.Entry(recent).State = System.Data.Entity.EntityState.Deleted;
                    dbo.SaveChanges();
                    res.code = "1";
                    res.message = "Archive file was successfully deleted.";
                }
                else
                {
                    res.code = "0";
                    res.message = "Archive file was not found, Please refresh list and try again.";
                }
            }

            var results = new JavaScriptSerializer().Serialize(res);
            return Json(results, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ArchiveSettings()
        {
            return View();
        }
        public ActionResult ScheduleReport()
        {
            string username = User.Identity.Name;
            List<ReportCategory> cats = ReportCore.get_reportcategory(username);
            ReportsDTO reports = new ReportsDTO();
            reports.cat_list = cats;
            return View(reports);
        }
        public ActionResult ScheduleReport_win(string report_id)
        {
            ViewBag.report_id = report_id;
            return View();
        }

        public JsonResult SaveReportScheduler(string report_id, string title, string desc, string from, string to, string repeatevery, string email, string increamental, string mo, string tu, string we, string th, string fr, string sa, string su, string output, string repeat)
        {
            AjaxResults res = new AjaxResults();

            DateTime _from = Convert.ToDateTime(from);
            DateTime _to = Convert.ToDateTime(to);

            using (lidEntities dbo = new lidEntities())
            {
                b_reportschedule schedule = new b_reportschedule();
                schedule.report_id = report_id.ToLongOrDefault(0);
                schedule.title = title;
                schedule.desc = desc;
                schedule.date_from = _from;
                schedule.date_to = _to;
                schedule.repeatevery = repeatevery.ToInt16OrDefault();
                schedule.email = email;
                schedule.increamental = increamental.ToBooleanOrDefault();
                schedule.mo = mo.ToBooleanOrDefault();
                schedule.tu = tu.ToBooleanOrDefault();
                schedule.we = we.ToBooleanOrDefault();
                schedule.th = th.ToBooleanOrDefault();
                schedule.fr = fr.ToBooleanOrDefault();
                schedule.sa = sa.ToBooleanOrDefault();
                schedule.su = su.ToBooleanOrDefault();
                schedule.output = output;
                schedule.repeat = repeat;
                schedule.date_created = DateTime.Now;
                schedule.deleted = false;
                schedule.owner = User.Identity.Name;

                dbo.b_reportschedule.Add(schedule);
                dbo.SaveChanges();
                res.code = "1";
            }
            var results = new JavaScriptSerializer().Serialize(res);
            return Json(results, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ManageSchedule()
        {
            //List<ReportScheduleDTO> archive = ReportCore.get_reportschedule(User.Identity.Name);
            return View();
        }

        public JsonResult GetManageSchedule()
        {
            string username = User.Identity.Name;
            List<ReportScheduleDTO> list = ReportCore.get_reportschedule(username);
            var json = new JavaScriptSerializer().Serialize(list);
            return Json(json, JsonRequestBehavior.AllowGet);
        }
        public JsonResult DelReportSchedule(string id)
        {
            AjaxResults res = new AjaxResults();
            using (lidEntities dbo = new lidEntities())
            {
                long _id = id.ToLongOrDefault(0);
                b_reportschedule recent = dbo.b_reportschedule.Where(x => x.id == _id).FirstOrDefault();
                if (recent != null)
                {
                    dbo.Entry(recent).State = System.Data.Entity.EntityState.Deleted;
                    dbo.SaveChanges();
                    res.code = "1";
                    res.message = "Report scheduler was successfully deleted.";
                }
                else
                {
                    res.code = "0";

web_app/Views/Reports/ArchivedReports.cshtml
@model IEnumerable<lid_web.Models.ArchiveDTO>
@{
    ViewBag.Title = "ArchivedReports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("..//partial//_side_menu_reports", null, new ViewDataDictionary { { "_current", "ArchivedReports" } })


<div class="centercontent">

    <div class="pageheader">
        <h1 class="pagetitle">Archived Reports</h1>
        <span class="pagedesc">View Reports Achived </span>
    </div>

    <div id="contentwrapper" class="contentwrapper nopadding">
        <div class="filemgr_content" style="margin-right: 20px !important;">

            <small>
                <strong>
                    <em>Tips: Hold Control key to select multiple items. To view file, select one item and click View File button.</em>
                </strong>
            </small>

            <br /><br />

            <div class="contenttitle3">
                <h3>&nbsp;Archive Report Files</h3>
            </div>
            <br /><br />
            <ul class="listfile">
                @foreach (lid_web.Models.ArchiveDTO archive in Model)
                {
                    <li class="col-md-2">
                        <a class="image text-center" download="" href="~/Files/ReportsArchivers/@archive.filename" style="min-height:220px">
                            <span class="img"><img style="width:95% !important" src="~/Assets/images/icon_right.png" alt="" /></span>
                            <h4 class="filename">@archive.description</h4>
                            <label>Create: @archive.arch_date At @archive.arch_time</label>
                        </a>
                    </li>
                }
            </ul>
            <br /><br />
            <br clear="all" />

        </div>



    </div>

</div>

web_app/Views/Reports/Index.cshtml
@model lid_web.Models.ReportsDTO
@using lid_web.BLL;
@using lid_web.Models;

@{
    ViewBag.Title = "Index";
}

@Html.Partial("..//partial//_side_menu_reports", null, new ViewDataDictionary { { "_current", "Index" } })


<div class="centercontent">

    <div class="pageheader">
        <h1 class="pagetitle">Reports Dashboard</h1>
        <span class="pagedesc">View and Print Organisation Reports</span>
    </div>
    <div id="contentwrapper" class="contentwrapper nopadding">
        <div class="filemgr">
            <div class="filemgr_left">
                <div class="filemgr_head">
                    <ul class="filemgr_menu">
                        @*<li><a class="prev prev_disabled"></a></li>
                        <li><a class="next"></a></li>*@
                        <li class="marginleft20"><a class="selectall">Select All</a></li>
                        <li class="marginleft5 viewfilebtn"><a class="preview preview_disabled">View File</a></li>
                        @*<li class="marginleft20 newfoldbtn"><a class="newfolder" title="Add New Foldr"></a></li>
                        <li class="marginleft5 trashbtn"><a class="trash trash_disabled" title="Trash"></a></li>*@
                        <li class="marginleft20 filesearch">
                            <form>
                                <input type="text" id="filekeyword" class="filekeyword" value="Search report here" />
                            </form>
                        </li>
                        @*<li class="right newfilebtn"><a href="" class="newfilebutton radius2">Add New Report</a></li>*@
                    </ul>
                    <span class="clearall"></span>
                </div><!--filemgr_head-->

                <div class="filemgr_category">
                    <ul>
                        @{
                            int tot = 0;
                            foreach (lid_web.Models.ReportCategory cat in Model.cat_list)
                            {
                                if (cat.reports_list.Count > 0)
                                {
                                    tot = tot + cat.reports_list.Count;
                                    <li><a href="#@cat.reportcat_id">@cat.report_cat (@cat.reports_list.Count)</a></li>
                                }
                            }
                            <li class="right"><span class="pagenuminfo"><strong>You have @tot Reports</strong> </span></li>
                        }
                    </ul>
                </div><!--filemgr_category-->

                <div class="filemgr_content">

                    <small>
                        <strong>
                            <em>Tips: Hold Control key to select multiple items. To view file, select one item and click View File button.</em>
                        </strong>
                    </small>

                    <br /><br />

                    @foreach (lid_web.Models.ReportCategory cat in Model.cat_list)
                    {
                        if (cat.reports_list.Count > 0)
                        {
                            <div class="contenttitle3" id="@cat.reportcat_id">
                                <h3>&nbsp;@cat.report_cat</h3>
                            </div>
                            <br /><br />
                            <ul class="listfile">
                                @foreach (lid_web.Models.Reports report in cat.reports_list)
                                {
                                    <li class="col-md-3">
                                        <a class="image text-center fancybox" href="@Url.Action("ReportParameters", "Reports", new { report_id = report.report_id })" style="min-height:220px">
                                            <span class="img"><img style="width:95% !important" src="~/Assets/images/reports/@report.report_image" alt="" /></span>
                                            <h4 class="filename">@report.report_name</h4>
                                            <label>@report.report_desc</label>
                                        </a>
                                    </li>
                                }
                            </ul>
                            <br /><br />
                        }
                    }
                    <br clear="all" />

                </div><!--filemgr_content-->

            </div><!--filemgr_left -->

            <div class="filemgr_right">
                <div class="filemgr_rightinner">
                    <div class="contenttitle2" style="margin-top: 0">
                        <h3>Recent Report</h3>
                    </div><!--contenttitle-->
                    <ul class="menuright">
                        @{
                            List<RptRecentDTO> recents = ReportCore.rpt_gettenresentreports(@User.Identity.Name);
                            foreach (RptRecentDTO recent in recents)
                            {
                                <li style="border-bottom:1px dashed gray"><a href="@recent.report_url">@recent.report_name <br /><i class="linkcolor small">@recent.report_date </i></a></li>
                            }
                        }
                    </ul>
                </div><!-- filemgr_rightinner -->
            </div><!-- filemgr_right -->
            <br clear="all" />
        </div><!--filemgr-->

    </div><!--contentwrapper-->
</div>

<script type="text/javascript">
    jQuery(document).ready(function () {

        jQuery('a.fancybox').click(function () {
            // debugger;
            jQuery.fancybox.open({
                'content': jQuery('<div>').load(jQuery(this).attr('href')),
                'autoScale': false,
                'autoDimensions': true,
                'transitionIn': 'none',
                'transitionOut': 'none',
                'hideOnOverlayClick': false,
                'hideOnContentClick': false,
                'showCloseButton': true,
                'type': 'iframe',
                'autoSize': false,
                'width': 850,
                'height': 450,
                helpers: {
                    overlay: { closeClick: false } // prevents closing when clicking OUTSIDE fancybox
                },
                'afterClose': function () {
                    window.location.reload();
                }
            });
            return false;
        });
    });
</script>

web_app/Views/Reports/ManageReports.cshtml
@model lid_web.Models.ReportsDTO
@using lid_web.BLL;
@using lid_web.Models;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("..//partial//_side_menu_reports", null, new ViewDataDictionary { { "_current", "ManageReports" } })


<div class="centercontent">

    <div class="pageheader">
        <h1 class="pagetitle">Manage Reports</h1>
        <span class="pagedesc">Remove and/or Add Reports From Dashboard Reports List </span>
    </div>

    <div id="contentwrapper" class="contentwrapper nopadding">
        <div class="filemgr">
            <div class="filemgr_left">
                <div class="filemgr_category">
                    <ul>
                        @{
                            int tot = 0;
                            foreach (lid_web.Models.ReportCategory cat in Model.cat_list)
                            {
                                tot = tot + cat.reports_list.Count;
                                <li><a href="#@cat.reportcat_id">@cat.report_cat (@cat.reports_list.Count)</a></li>
                            }
                            <li class="right"><span class="pagenuminfo"><strong>You have @tot Reports</strong> </span></li>
                        }
                    </ul>
                </div><!--filemgr_category-->

                <div class="filemgr_content" style="margin-right: 20px !important;">

                    <small>
                        <strong>
                            <em>&nbsp;Tips: Click on report item to toggle between Add and Remove, light green indicate active/showing and light red indicate inactive/hidden.</em>
                        </strong>
                    </small>

                    <br /><br />

                    @foreach (lid_web.Models.ReportCategory cat in Model.cat_list)
                    {

                        <div class="contenttitle3" id="@cat.reportcat_id">
                            <h3>&nbsp;@cat.report_cat</h3>
                        </div>
                        <br /><br />
                        <ul class="listfile">
                            @foreach (lid_web.Models.Reports report in cat.reports_list)
                            {
                                string css = (report.report_toggled) ? "bg-warning" : "bg-success";
                                <li class="col-md-2 @css">
                                    <a class="image text-center" onclick="toggleReport(this,'@report.report_id','@report.report_name')" style="min-height:220px">
                                        <span class="img"><img style="width:95% !important" src="~/Assets/images/reports/@report.report_image" alt="" /></span>
                                        <h4 class="filename">@report.report_name</h4>
                                        <label>@report.report_desc</label>
                                    </a>
                                </li>
                            }
                        </ul>
                        <br /><br />

                    }
                    <br clear="all" />

                </div>

            </div>
        </div>

    </div>
</div>



<script type="text/javascript">
    jQuery(document).ready(function () {
    });

    function toggleReport(tag,id,name)
    {
        jQuery.ajax({
            url: '/Reports/ToggleReport',
            dataType: "json",
            type: "POST",
            data: JSON.stringify({id: id}),
            contentType: 'application/json; charset=utf-8',
            async: false,
            success: function (response, newValue) {
                var data = JSON.parse(response);
                if (data.code == 1) {
                    var msg = data.message;
                    jQuery.growl.notice({ title: name, message: msg });
                }
                else {
                    var msg = data.message;
                    jQuery.growl.warning({ title: name, message: msg });
                }
                var li = jQuery(tag.parentElement);

                if (jQuery(li).hasClass('bg-success')) {
                    jQuery(li).removeClass('bg-success');
                    jQuery(li).addClass('bg-warning');
                }
                else {
                    jQuery(li).removeClass('bg-warning');
                    jQuery(li).addClass('bg-success');
                }
            },
            error: function (xhr, thrownError, thrownError) {
                var msg = "Message: " + thrownError;
                jQuery.growl.error({ title: "Exception", message: msg });
            }
        });
    }
</script>

web_app/Views/Reports/RecentReports.cshtml
@model IEnumerable<lid_web.Models.RptRecentDTO>
@{
    ViewBag.Title = "RecentReports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("..//partial//_side_menu_reports", null, new ViewDataDictionary { { "_current", "RecentReports" } })



<div class="centercontent">

    <div class="pageheader">
        <h1 class="pagetitle">Recent Reports</h1>
        <span class="pagedesc">View Reports Recently Oponed</span>
    </div>

    <div id="contentwrapper" class="contentwrapper nopadding">
        <div class="filemgr_content" style="margin-right: 20px !important;">

            <small>
                <strong>
                    <em>Tips: Hold Control key to select multiple items. To view file, select one item and click View File button.</em>
                </strong>
            </small>

            <br /><br />

            <div class="contenttitle3">
                <h3>&nbsp;Recent Report List</h3>
            </div>
            <br /><br />
            <ul class="listfile">
                @foreach (lid_web.Models.RptRecentDTO report in Model)
                {
                    <li class="col-md-2">
                        <a class="image text-center " href="@report.report_url" style="min-height:220px">
                            <i class="linkcolor small"><strong>Date Opened: @report.report_date </strong> </i>
                            <span class="img"><img style="width:95% !important" src="~/Assets/images/reports/@report.report_image" alt="" /></span>
                            <h4 class="filename">@report.report_name</h4>
                            <label>@report.report_desc</label>
                        </a>
                    </li>
                }
            </ul>
            <br /><br />
            <br clear="all" />

        </div>







    </div>
</div>

web_app/Views/Reports/ReportParameters.cshtml
@model lid_web.Models.Reports

@{
    Layout = "~/Views/Shared/_Popup.cshtml";
}


<div class="centercontent1">

    <div class="pageheader">
        <span class="profilepic"><img src="~/Assets/Images/icon_right.png" alt="" /></span>
        <div class="profiletitle">
            <h1 class="pagetitle">Report: @Model.report_name </h1>
            <span class="pagedesc">Complete report parameters</span>
        </div>
    </div><!--pageheader-->
    <div id="contentwrapper" class="contentwrapper" style="background-color: #fff !important">
        <div class="stdform">
            <input type="hidden" id="report_id" value="@Model.report_id" />
            <input type="hidden" id="report_file" value="@Model.report_file" />
            <table class="table">

                @Html.Partial("..//Reports//Parameters//" + @Model.report_parms, null, new ViewDataDictionary { { "report_id", @Model.report_id } })
                <tr>
                    <td>Archive This Report</td>
                    <td></td>
                    <td>
                        <input type="checkbox" name="name" id="chkArchive" />

                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>
                        <!-- Split button -->
                        <div class="btn-group dropup">
                            <button type="button" class="btn btn-default" id="btnReport" onclick="getReport();">Download As PDF</button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li class="disabled"><a href="#">View Report Online</a></li>
                                <li><a href="javascript:getReport();">Download As PDF</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#" class="disabled">Email Report To Me</a></li>
                            </ul>
                        </div>
                        <button class="submit0 stdbtn" id="btnReport" onclick="getReport();">Get Report</button>
                        <a id="link_pdf"></a>
                        <input type="hidden" name="structure_id" id="structure_id" />
                    </td>
                </tr>
            </table>
        </div>

    </div>
</div>

<script>

    jQuery(document).ready(function () {
        byteFile.init();

        jQuery('#structure_level').tree({
            categories: ['Department'],
            source: '/Ajax/GetTreeStructure',
            parent: 'parentId',
            value: 'id',
            text: 'name',
            drop: true,
            multi: false,
            all: false,
            include: ['Department'],
            highlight: '#CCFFEB',
            placeholder: 'Select department or positions..',
            bound: function (data) {
            },
            changed: function (item) {
                var _organisation = jQuery('#structure_level').data('tree').list;
                jQuery('#structure_id').val(_organisation);
            }
        });


        jQuery("#datefrom").kendoDatePicker({
            value: new Date(),
            format: "dd MMM yyyy"
        });
        jQuery("#dateto").kendoDatePicker({
            value: new Date(),
            format: "dd MMM yyyy"
        });
    });

    function openReport(parameters) {
        var report_id = jQuery('#report_id').val();
        var report_file = jQuery('#report_file').val();
        var archive = jQuery('#chkArchive')[0].checked;
        var url = report_file + "?archive=" + archive;
        console
        var report_url = '/Reports/' + url + parameters;
        console.log('report_url')
        console.log(report_url)
        var link = jQuery('#link_pdf')[0];
        jQuery(link).attr('href', report_url);
        jQuery(link).attr('download', 'true');
        link.click();

        var msg = "Report was sucessfully geranted."
        jQuery.growl.notice({ title: "Report", message: msg });

        jQuery.ajax({
            url: "/Reports/LogRecentReport",
            type: "POST",
            data: { report_id: report_id, report_url: report_url }
        })
        .done(function () {
            var msg = "Report was added to recent list."
            jQuery.growl.notice({ title: "Saved", message: msg });
        });

    }
</script>