web_app/Controllers/BIController.cs
using Dapper;
using web_app.BLL;
using web_app.DAL;
using web_app.Models;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace web_app.Controllers
{
    [Authorize]
    public class BIController : Controller
    {
        private static string ConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ToString();

        private static SqlConnection GetOpenConnection(bool mars = false)
        {
            var cs = ConnectionString;
            if (mars)
            {
                var scsb = new SqlConnectionStringBuilder(cs)
                {
                    MultipleActiveResultSets = true
                };
                cs = scsb.ConnectionString;
            }
            var connection = new SqlConnection(cs);
            connection.Open();
            return connection;
        }

        public ActionResult Index()
        {
            string username = User.Identity.Name;
            List<ReportCategory> cats = ReportCore.get_reportcategory(username);
            ReportsDTO reports = new ReportsDTO();
            reports.cat_list = cats;
            return View(reports);
        }
        public ActionResult ReportParameters(long report_id)
        {
            Reports report = ReportCore.get_report(report_id);
            return View(report);
        }
        public ActionResult passreport()
        {
            List<PassFailReportDTO> res = new List<PassFailReportDTO>();
            using (lidEntities dbo = new lidEntities())
            {
                using (var cn = GetOpenConnection())
                {
                    string username = User.Identity.Name.ToString();
                    res = cn.Query<PassFailReportDTO>("rpt_get_passinspection", new { username = username }, commandType: CommandType.StoredProcedure).ToList();
                }
            }
            return View(res);
        }
        public ActionResult failreport()
        {
            return View();
        }
        public ActionResult assetlist()
        {
            return View();
        }

        public JsonResult GetPassReport()
        {
            List<PassFailReportDTO> res = new List<PassFailReportDTO>();
            using (lidEntities dbo = new lidEntities())
            {
                using (var cn = GetOpenConnection())
                {
                    string username = User.Identity.Name.ToString();
                    res = cn.Query<PassFailReportDTO>("rpt_get_passinspection", new { username = username }, commandType: CommandType.StoredProcedure).ToList();
                }
            }

            var results = new JavaScriptSerializer().Serialize(res);
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PassFailReport(string id)
        {
            PassFailReportDTO inspections = new PassFailReportDTO();

            using (var cn = GetOpenConnection())
            {
                string username = User.Identity.Name.ToString();
                //long id = 1;
                inspections = cn.Query<PassFailReportDTO>("rpt_get_passinspection_byid", new { inspection_id = id }, commandType: CommandType.StoredProcedure).FirstOrDefault();

                if (inspections.company_logo != null)
                {
                    string imreBase64Data = Convert.ToBase64String(inspections.company_logo);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    inspections.company_logo_data = imgDataURL;
                }
                if (inspections.inspection_image != null)
                {
                    //string imreBase64Data = Convert.ToBase64String(inspections.inspection_image);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", inspections.inspection_image);
                    inspections.inspection_image_data = imgDataURL;
                }
                if (inspections.item_image != null)
                {
                    string imreBase64Data = Convert.ToBase64String(inspections.item_image);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    inspections.item_image_data = imgDataURL;
                }
                if (inspections.signature_img != null)
                {
                    string imreBase64Data = Convert.ToBase64String(inspections.signature_img);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    inspections.signature_data = imgDataURL;
                }

            }

            List<PassFailReportItemsDTO> lines = new List<PassFailReportItemsDTO>();
            using (var cn = GetOpenConnection())
            {
                string username = User.Identity.Name.ToString();
                lines = cn.Query<PassFailReportItemsDTO>("rpt_get_passinspection_items", new { inspection_id = inspections.inspection_id }, commandType: CommandType.StoredProcedure).ToList();
            }
            inspections.line_items = lines;


            string footer = string.Format("--print-media-type --footer-line --header-line --header-font-size 8 --footer-font-size 8 --footer-center \"{0}\" --footer-left \"{1}\" --footer-right \"Page [page] of [toPage]\"",
               DateTime.Now.ToShortDateString() + "   " + DateTime.Now.ToShortTimeString(), "Printed By:" + User.Identity.Name);

            //return View(inspections);

            return new ViewAsPdf("PassFailReport", inspections)
            {
                FileName = "InpectionReport" + inspections.inspection_id + ".pdf",
                CustomSwitches = footer,
                PageSize = Size.A4,
                //PageOrientation = Orientation.Landscape,
            };
        }
        public ActionResult PassFailCert(string id)
        {
            PassFailReportDTO inspections = new PassFailReportDTO();

            using (var cn = GetOpenConnection())
            {
                string username = User.Identity.Name.ToString();
                //long id = 1;
                inspections = cn.Query<PassFailReportDTO>("rpt_get_passinspection_byid", new { inspection_id = id }, commandType: CommandType.StoredProcedure).FirstOrDefault();
                if (inspections.company_logo != null)
                {
                    string imreBase64Data = Convert.ToBase64String(inspections.company_logo);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    inspections.company_logo_data = imgDataURL;
                }
                if (inspections.inspection_image != null)
                {
                    //string imreBase64Data = Convert.ToBase64String(inspections.inspection_image);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", inspections.inspection_image);
                    inspections.inspection_image_data = imgDataURL;
                }
                if (inspections.item_image != null)
                {
                    string imreBase64Data = Convert.ToBase64String(inspections.item_image);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    inspections.item_image_data = imgDataURL;
                }
                if (inspections.signature_img != null)
                {
                    string imreBase64Data = Convert.ToBase64String(inspections.signature_img);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    inspections.signature_data = imgDataURL;
                }
            }

            List<PassFailReportItemsDTO> lines = new List<PassFailReportItemsDTO>();
            using (var cn = GetOpenConnection())
            {
                string username = User.Identity.Name.ToString();
                lines = cn.Query<PassFailReportItemsDTO>("rpt_get_passinspection_items", new { inspection_id = inspections.inspection_id }, commandType: CommandType.StoredProcedure).ToList();
            }
            inspections.line_items = lines;


            string footer = string.Format("--print-media-type --footer-line --header-line --header-font-size 8 --footer-font-size 8 --footer-center \"{0}\" --footer-left \"{1}\" --footer-right \"Page [page] of [toPage]\"",
               DateTime.Now.ToShortDateString() + "   " + DateTime.Now.ToShortTimeString(), "Printed By:" + User.Identity.Name);

            //return View(inspections);

            return new ViewAsPdf("PassFailCert", inspections)
            {
                FileName = "InpectionCertificate" + inspections.inspection_id + ".pdf",
                CustomSwitches = footer,
                PageSize = Size.A4,
                //PageOrientation = Orientation.Landscape,

            };
        }
       public ActionResult PassFailView(string id)
        {
            PassFailReportDTO inspections = new PassFailReportDTO();

            using (var cn = GetOpenConnection())
            {
                string username = User.Identity.Name.ToString();
                //long id = 1;
                inspections = cn.Query<PassFailReportDTO>("rpt_get_passinspection_byid", new { inspection_id = id }, commandType: CommandType.StoredProcedure).FirstOrDefault();
                if (inspections.company_logo != null)
                {
                    string imreBase64Data = Convert.ToBase64String(inspections.company_logo);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    inspections.company_logo_data = imgDataURL;
                }
                if (inspections.inspection_image != null)

web_app/Views/Shared/_Anon.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Lifting::Id</title>
    <link rel="stylesheet" href="~/Assets/css/style.default.css" type="text/css" />
    <link rel="stylesheet" href="~/Assets/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/Assets/css/plugins/jquery.alerts.css" type="text/css" />
    <link rel="stylesheet" href="~/Assets/js/fancybox/jquery.fancybox.css" type="text/css" />
    @*<link rel="stylesheet" href="~/Assets/css/plugins/jquery.jgrowl.min.css" type="text/css" />*@
    <link rel="stylesheet" href="~/Assets/css/dt_picker.css" type="text/css" />


    <script type="text/javascript" src="/Assets/js/jquery/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="/Assets/js/jquery-ui.min.js"></script>
    @*<script type="text/javascript" src="/Assets/js/plugins/jquery-ui-1.8.16.custom.min.js"></script>*@
    <script type="text/javascript" src="/Assets/js/plugins/jquery.cookie.js"></script>
    @*<script type="text/javascript" src="/Assets/js/plugins/jquery.uniform.min.js"></script>*@

    <script type="text/javascript" src="/Assets/js/plugins/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/Assets/js/plugins/jquery.slimscroll.js"></script>
    @*<script type='text/javascript' src='/Assets/js/plugins/fullcalendar.min.js'></script>*@

    <script type="text/javascript" src="/Assets/js/plugins/jquery.dataTables.min.js"></script>
    @*<script type="text/javascript" src="/Scripts/jquery.uniform.min.js"></script>*@

    <script type="text/javascript" src="/Assets/js/custom/general.js"></script>
    @*<script type="text/javascript" src="/Assets/js/plugins/jquery.jgrowl.min.js"></script>*@
    <script type="text/javascript" src="/Assets/js/plugins/jquery.alerts.js"></script>

    <script type="text/javascript" src="/Assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Assets/js/fancybox/jquery.fancybox.js"></script>

    <link href="~/Assets/js/plugins/jquery.growl/stylesheets/jquery.growl.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/Assets/js/plugins/jquery.growl/javascripts/jquery.growl.js"></script>
    @*<link rel="stylesheet" type="text/css" href="~//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.4.1/jquery.jgrowl.min.css" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.4.1/jquery.jgrowl.min.js"></script>*@
    <style type="text/css">
        .green_color {
            color: green !important;
        }

        .blue_color {
            color: blue !important;
        }
    </style>
</head>

<body class="loginpage0">
    <div>


        @RenderBody()

    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

web_app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Lifting::Id</title>
    <link rel="stylesheet" href="/Assets/css/style.default.css" type="text/css" />
    <link rel="stylesheet" href="/Assets/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="/Assets/css/plugins/jquery.alerts.css" type="text/css" />
    <link rel="stylesheet" href="/Assets/js/fancybox/jquery.fancybox.css" type="text/css" />
    <link href="/Assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="/Assets/css/plugins/jquery.jgrowl.min.css" type="text/css" />*@
    <link rel="stylesheet" href="/Assets/css/dt_picker.css" type="text/css" />
    <link href="~/Assets/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" />
    @*<link href="/Scripts/bootstrap-datetimepicker.css" rel="stylesheet" />*@
    @*<link href="/Scripts/prettify-1.0.css" rel="stylesheet" />*@
    @*<link href="/Scripts/getorgchart.css" rel="stylesheet" />*@
    <link href="/Assets/css/plugins/datatables.css" rel="stylesheet" />

    @*<link href="~/Content/custom.css" rel="stylesheet" />*@
    <script type="text/javascript" src="/Assets/kendo/jquery.min.js"></script>
    @*<script type="text/javascript" src="/Assets/js/jquery/jquery-1.10.1.min.js"></script>
        <script type="text/javascript" src="/Assets/js/jquery-ui.min.js"></script>*@
    <script type="text/javascript" src="/Assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Assets/js/fancybox/jquery.fancybox.js"></script>
    @*<script type="text/javascript" src="/Assets/js/plugins/jquery-ui-1.8.16.custom.min.js"></script>*@
    <script type="text/javascript" src="/Assets/js/plugins/jquery.cookie.js"></script>
    @*<script type="text/javascript" src="/Assets/js/plugins/jquery.uniform.min.js"></script>*@

    @* <script type="text/javascript" src="/Assets/js/plugins/jquery.validate.min.js"></script>
          <script type="text/javascript" src="/Assets/js/plugins/jquery.slimscroll.js"></script>
        <script type='text/javascript' src='/Assets/js/plugins/fullcalendar.min.js'></script>*@

    <script type="text/javascript" src="/Assets/js/plugins/jquery.dataTables.js"></script>
    @*   <script type="text/javascript" src="/Assets/js/plugins/jquery.uniform.min.js"></script>*@

    <script type="text/javascript" src="/Assets/js/custom/general.js"></script>

    @*<script type="text/javascript" src="/Assets/js/custom/elements.js"></script>
        <script type="text/javascript" src="/Assets/js/plugins/jquery.jgrowl.min.js"></script>*@
    <script type="text/javascript" src="/Assets/js/plugins/jquery.alerts.js"></script>
    @*<script type="text/javascript" src="/Assets/js/comboTreePlugin.js"></script>*@

    @*<script src="/Scripts/bootstrap-datetimepicker.js"></script>*@
    @*<script src="/Scripts/prettify-1.0.min.js"></script>*@
    <link href="/Assets/js/plugins/jquery.growl/stylesheets/jquery.growl.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/Assets/js/plugins/jquery.growl/javascripts/jquery.growl.js"></script>
    @*<script type="text/javascript" src="~/Assets/bootstrap3-editable/js/bootstrap-editable.js"></script>*@
    @*<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.4.1/jquery.jgrowl.min.css" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.4.1/jquery.jgrowl.min.js"></script>*@
    @* <script src="/Assets/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
        <script src="/Scripts/getorgchart.js"></script>*@

    <link rel="stylesheet" type="text/css" href="/Assets/plugins/jstree/dist/themes/default/style.min.css" />
    <script type="text/javascript" src="/Assets/plugins/jstree/dist/jstree.min.js"></script>
    @*<link type="text/css" href="/Assets/plugins/jquerytree/css/jquery.tree.css" rel="stylesheet" />
        <script type="text/javascript"  src="/Assets/plugins/jquerytree/js/jquery.tree.js"></script>*@


    @*<link rel="stylesheet" type="text/css" href="~/Assets/plugins/hierarchy/hierarchy-select.scss" />
          <script type="text/javascript" src="~/Assets/plugins/hierarchy/hierarchy-select.js"></script>
        <script src="/Assets/plugins/jlinq/lib/jlinq.js"></script>
          <script src="/Assets/js/jstree.js"></script>
        <script src="http: //kendo.cdn.telerik.com/2019.1.220/js/jszip.min.js"></script>*@

    <link href="/Assets/kendo/kendo.common.min.css" rel="stylesheet" />
    <link href="/Assets/kendo/kendo.default.min.css" rel="stylesheet" />

    <script src="/Assets/kendo/jszip.min.js"></script>
    <script src="/Assets/kendo/kendo.all.min.js"></script>
    <style type="text/css">
        .green_color {
            color: green !important;
        }

        .blue_color {
            color: blue !important;
        }

        .red_color {
            color: red !important;
        }

        .weekend {
            background-color: silver !important;
        }

        #treeview .k-sprite {
            background-image: url("/Assets/images/coloricons-sprite.png");
        }

        .rootfolder {
            background-position: 0 0;
        }

        .folder {
            background-position: 0 -16px;
        }

        .pdf {
            background-position: 0 -32px;
        }

        .html {
            background-position: 0 -48px;
        }

        .image {
            background-position: 0 -64px;
        }
    </style>

</head>

<body class="withvernav">
    <div class="bodywrapper">
        <div class="topheader">
            <div class="left">
                <h1 class="logo">LIFTING<span>.ID</span></h1>
                <span class="slogan">Item management</span>

                <!--if (ViewBag.NoRole == null)
                {
                    <div class="search">
                        <div>
                            <input type="text" name="keyword" id="keyword" value="Enter keyword(s)" />
                            <button class="submitbutton"></button>
                        </div>
                    </div>
                }
                search-->

                <br clear="all" />

            </div>
            <!--left-->
            @*@if (ViewBag.NoRole == null)
                {*@
            <div class="right">
                <div class="notification">
                    @* <a class="count" href="ajax/notifications.html"><span> <i class="icon icon-message">9</i> </span></a>*@
                </div>
                <div class="userinfo">
                    <img src="/Assets/images/thumbs/avatar.png" alt="" style="width:32px; height:32px" />
                    <span>@User.Identity.Name</span>
                </div>
                <!--userinfo-->

                <div class="userinfodrop">
                    <div class="avatar">
                        <a href="#">
                            <img src="/Assets/images/thumbs/avatar.png" alt="" style="width:64px; height:64px" />
                        </a>
                    </div>
                    <!--avatar-->
                    <div class="userdata">
                        <h4>@User.Identity.Name </h4>
                        <span class="email"> @User.Identity.Name  </span>
                        <ul>
                            <li><a href="@Url.Action("ChangePassword", "Profile")">Change Password</a></li>
                            <li><a href="@Url.Action("LogOut", "Account")">Sign Out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            @*  *@
            <!--right-->
        </div>

        <div class="header">

            @Html.Partial("..//partial//_top_main_menus", null, null)
            <div class="headerwidget2">
                <div class="earnings">
                    <div style="padding:0; margin:0" class="date">@DateTime.Today.ToString("dd MMM yyyy")</div>
                    <div class="one_half">
                        <h4 style="padding:0; margin:0">Total Assets</h4>
                        <h2 style="margin-top:2px !important; font-size:38px !important">
                            <a class="popupbox" href="@Url.Action("passreport", "BI", null)">
                                <span id="span_countassets">--</span>
                            </a>
                        </h2>
                    </div>
                    <div class="one_half last">
                        <h4 style="padding:0; margin:0">Total Inspection</h4>
                        <h2 style="margin-top:2px !important; font-size:38px !important">
                            <a class="popupbox" href="@Url.Action("ViewAssets", "Company", null)">
                                <span id="get_countinspection">--</span>
                            </a>
                        </h2>
                    </div>
                </div>
            </div>
        </div>
        @RenderBody()
    </div>
    <footer style="position:absolute; bottom:0px; display:none">
        App Version: @System.Reflection.Assembly.GetExecutingAssembly().GetName().Version
    </footer>


    @*<div id='ajax_loader'>
            <div>&nbsp;</div>
            <img src="/Assets/images/loading_blue.gif" />
        </div>*@
</body>
</html>
<script>

    jQuery(document).ready(function () {
        //jQuery(document).ajaxStop(function () {
        //    jQuery("#ajax_loader").hide();
        //});
        //jQuery(document).ajaxStart(function () {
        //    jQuery("#ajax_loader").show();
        //});
        //jQuery.fn.editable.defaults.mode = 'inline';
        //jQuery('.datepicker').editable({
        //    format: 'yyyy-mm-dd',
        //    viewformat: 'dd/mm/yyyy',
        //    datepicker: {
        //        weekStart: 1
        //    }
        //});

        jQuery.ajax({
            url: "/Ajax/get_countassets",
            type: "POST",
            dataType: "json",
            contentType: 'application/json; charset=utf-8',
            // async: false,
        })
            .done(function (data) {
                jQuery("#span_countassets").text(data);
            });
        jQuery.ajax({
            url: "/Ajax/get_countinspection",
            type: "POST",
            dataType: "json",
            contentType: 'application/json; charset=utf-8',
            //async: false,
        })
            .done(function (data) {
                jQuery("#span_countinspection").text(data);
            });

        jQuery('a.popupbox').click(function () {
            jQuery.fancybox.open({
                'content': jQuery('<div>').load(jQuery(this).attr('href')),
                'autoScale': false,
                'autoDimensions': true,
                'transitionIn': 'none',
                'transitionOut': 'none',
                'hideOnOverlayClick': false,
                'hideOnContentClick': false,
                'showCloseButton': true,
                'type': 'iframe',
                'autoSize': false,
                'width': 1100,
                'height': 600,
                helpers: {
                    overlay: { closeClick: false } // prevents closing when clicking OUTSIDE fancybox
                },
                'afterClose': function () {
                    // window.location.reload();
                }
            });
            return false;
        });

        jQuery('div.popupbox').click(function () {
            jQuery.fancybox.open({
                'content': jQuery('<div>').load(jQuery(this).attr('href')),
                'autoScale': false,
                'autoDimensions': true,
                'transitionIn': 'none',
                'transitionOut': 'none',
                'hideOnOverlayClick': false,
                'hideOnContentClick': false,
                'showCloseButton': true,
                'type': 'iframe',
                'autoSize': false,
                'width': 1100,
                'height': 600,
                helpers: {
                    overlay: { closeClick: false } // prevents closing when clicking OUTSIDE fancybox
                },
                'afterClose': function () {
                    window.location.reload();
                }
            });
            return false;
        });

    });
</script>

web_app/Views/Shared/_Popup.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>
    @*<link rel="stylesheet" href="/Assets/css/style.default.css" type="text/css" />
    <link rel="stylesheet" href="/Assets/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="/Assets/css/plugins/jquery.alerts.css" type="text/css" />
    <link rel="stylesheet" href="/Assets/js/fancybox/jquery.fancybox.css" type="text/css" />
    <link href="/Assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/Assets/kendo/kendo.common.min.css" rel="stylesheet" />
    <link href="/Assets/kendo/kendo.default.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="/Assets/css/dt_picker.css" type="text/css" />
    <link href="/Assets/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" />
    <link href="/Scripts/prettify-1.0.css" rel="stylesheet" />
    <link href="/Scripts/getorgchart.css" rel="stylesheet" />
    <link href="/Assets/css/plugins/datatables.css" rel="stylesheet" />

    <link href="~/Content/custom.css" rel="stylesheet" />
    <script type="text/javascript" src="/Assets/js/jquery/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="/Assets/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/Assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Assets/js/fancybox/jquery.fancybox.js"></script>
    <script type="text/javascript" src="/Assets/js/plugins/jquery.cookie.js"></script>

    <script type="text/javascript" src="/Assets/js/plugins/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/Assets/js/plugins/jquery.slimscroll.js"></script>

    <script type="text/javascript" src="/Assets/js/plugins/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/Scripts/jquery.uniform.min.js"></script>

    <script type="text/javascript" src="/Assets/js/custom/general.js"></script>
    <script type="text/javascript" src="/Assets/js/plugins/jquery.alerts.js"></script>

    <script src="/Scripts/prettify-1.0.min.js"></script>
    <link href="/Assets/js/plugins/jquery.growl/stylesheets/jquery.growl.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/Assets/js/plugins/jquery.growl/javascripts/jquery.growl.js"></script>
    <script src="/Assets/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
    <script src="/Scripts/getorgchart.js"></script>
    
    <script src="/Assets/kendo/kendo.all.min.js"></script>
    <style type="text/css">
        .green_color {
            color: green !important;
        }

        .blue_color {
            color: blue !important;
        }

        .weekend {
            background-color: silver !important;
        }

        #treeview .k-sprite {
            background-image: url("/Assets/images/coloricons-sprite.png");
        }

        .rootfolder {
            background-position: 0 0;
        }

        .folder {
            background-position: 0 -16px;
        }

        .pdf {
            background-position: 0 -32px;
        }

        .html {
            background-position: 0 -48px;
        }

        .image {
            background-position: 0 -64px;
        }
    </style>*@

</head>
<body class="withvernav">
    <div class="bodywrapper">
        @RenderBody()
    </div>
</body>
</html>